FROM openjdk:21-ea-11-slim-bullseye
# Instalar Docker
#RUN apt-get update && \
#    apt-get install -y docker.io
WORKDIR /app
COPY target/demo-1.0-SNAPSHOT.jar /app/app.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/app.jar"]
