version: '3'

services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: archivos
    ports:
      - "5432:5432"
    volumes:
      -  db_data:/var/lib/postgresql/data
      - ./create-database.sql:/create-database.sql  
    networks:
      - p2p_network

networks:
  p2p_network:
    external: true

volumes:
  db_data:
